# Generated by Django 5.0 on 2023-12-28 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, null=True)),
                ("email", models.CharField(max_length=100, null=True)),
                ("picture", models.ImageField(default="noprofile.jpg", upload_to="")),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pasteitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, null=True)),
                ("pasteitems", models.TextField(null=True)),
                ("added_time", models.DateField(auto_now_add=True, null=True)),
                (
                    "languages",
                    models.CharField(
                        choices=[
                            ("py", "python"),
                            ("C++", "Cplusplus"),
                            ("C", "Cprogramming"),
                            ("java", "Java"),
                            ("txt", "Text"),
                        ],
                        default="python",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "visible",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="Public",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pastebin.customer",
                    ),
                ),
            ],
        ),
    ]
