# Generated by Django 4.0.1 on 2022-02-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_remove_pasteitem_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='socialaccounts_links',
        ),
        migrations.AddField(
            model_name='pasteitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pastebin.users'),
        ),
    ]
