# Generated by Django 4.0.1 on 2022-01-29 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteitem',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pasteitem',
            name='languages',
            field=models.CharField(choices=[('py', 'python'), ('C++', 'Cplusplus'), ('C', 'Cprogramming'), ('java', 'Java'), ('txt', 'Text')], default='python', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pasteitem',
            name='visible',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='Public', max_length=100, null=True),
        ),
    ]
